version: '3.8'

services:
  react-app:
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - REACT_APP_BUILD_ENV=${REACT_APP_BUILD_ENV}
    ports:
      - "${REACT_APP_PORT}:${REACT_APP_PORT}"
    environment:
      - REACT_APP_BUILD_ENV=${REACT_APP_BUILD_ENV}
      - REACT_APP_PORT=${REACT_APP_PORT}
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
